name: Docker-Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to GitLab
        with:
          registry: oauth
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
