name: Docker-Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v2
        name: Build the Docker image
        with:
          registry: cr.yandex
          username: json_key
          password: AQAAAAAcQBsSAATuwWAXbNySKEPTj26_gZ9_kBk
      - run: docker build -t cr.yandex/crpqsamgcnl010de07sa/yc-cr-github-action:github.sha . #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - run: docker push cr.yandex/crpqsamgcnl010de07sa/yc-cr-github-action:github.sha #cr.yandex/crpqsamgcnl010de07sa/ubuntu:hello
