name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Log in to YC
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: oauth
          password: AQAAAAAcQBsSAATuwWAXbNySKEPTj26_gZ9_kBk
      -
         name: Build, tag, and push image to Yandex Cloud Container Registry
         run: |
          docker build -t cr.yandex/crpqsamgcnl010de07sa/time:latest .
          docker push cr.yandex/crpqsamgcnl010de07sa/time:latest
